# Generated by Django 5.0.2 on 2024-02-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genero_livros_teste_livros_titulo_generolivro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='teste',
        ),
    ]
